x-shared-enviroment-between-producer-and-consumer: &common-environment-producer-consumer
  BROKER_HOST: broker
  BROKER_PORT: "${BROKER_PORT}"
  EVENTS_KEY: "${EVENTS_KEY}"
  TOPIC_ID: "${TOPIC_ID}"

services:
  coordinator:
    container_name: coordinator
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_PORT}"
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:7.3.0

  broker:
    container_name: broker
    depends_on:
    - coordinator
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:${BROKER_PORT},PLAINTEXT_INTERNAL://broker:29092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "coordinator:${ZOOKEEPER_PORT}"
    image: confluentinc/cp-kafka:7.3.0

  init-broker:
    command: "sleep 30"
    depends_on:
    - broker
    image: python:3.10.9

  producer:
    build:
      context: ./producer
    depends_on:
      init-broker:
        condition: service_completed_successfully
    environment:
      << : *common-environment-producer-consumer

  consumer:
    build:
      context: ./consumer
    depends_on:
      init-broker:
        condition: service_completed_successfully
    environment:
      << : *common-environment-producer-consumer
      CONSUMER_APPLICATION_PORT:
      CONSUMER_GROUP_ID: "stock-prices-chart-service"
    ports:
    - "${CONSUMER_APPLICATION_PORT}:${CONSUMER_APPLICATION_PORT}"
